source 'https://rubygems.org'

gem 'sinatra'
gem 'bson_ext'
gem 'rspec'
gem 'activesupport', "~> 4.0.2"
gem 'mongo'
gem 'json'
gem 'sinatra-base'
gem 'sinatra-contrib'
gem 'nokogiri'
gem 'rest-client'
gem 'test-unit'
gem 'rack-test'
gem 'prawn'
