source :rubygems

gem 'net-http'
gem 'sinatra'
gem 'bson_ext'
gem 'rspec'
gem 'active_support-core_ext'
gem 'mongo'
gem 'date'
gem 'json-ext'
gem 'sinatra-base'
gem 'nokogiri'
gem 'rest-client'
gem 'test-unit'
gem 'rack-test'
gem 'prawn'
